title: 人民城轨2.0运营管理后台
description: 人民城轨2.0运营管理系统，提供直播管理、用户管理、审核管理等功能
baseurl: "/renmin-chenggui-admin"
url: "https://kcaaaa.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
source: .
destination: _site

# Exclude from processing
exclude:
  - 参考资料/
  - "*.xlsx"
  - "*.docx"
  - "*.pptx"
  - README.md
  - .gitignore
  - .git/
  - .github/

# Include files
include:
  - .nojekyll
  - js/
  - index.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Disable Jekyll processing for JavaScript files
sass:
  style: compressed

# Keep files
keep_files:
  - js/
  - index.html 